### ISSUE TITLE
Text jumping when cycling through games

### ISSUE THREAD

**Issue by WizLizard** [Asnivor/MedLaunch#175] opened 2017-08-26 03:40 UTC
When clicking on multiple games in my library i see text jumping outside the boundaries of the right sidebar that displays the games info and boxart.

**Comment by Asnivor** [comment] 2017-08-30 07:47
Yup, confirmed. I guess I need to add an auto-horizontal scrollbar around that text (the same as has been done with the 'game stats' box above.

**Comment by Asnivor** [comment] 2017-08-30 09:24
Should now be fixed in the upcoming release (possibly tonight, maybe tomorrow morning)

**Comment by WizLizard** [comment] 2017-09-25 16:39
Been patiently waiting for this release, really looking forward to it!

**Comment by WizLizard** [comment] 2017-09-27 00:21
This doesn't seem fixed in latest stable release. Text keeps jumping to the right when clicking through my game list.

**Comment by Asnivor** [comment] 2017-09-27 04:50
Hi.

I'm either struggling to reproduce this, or I am misunderstanding the actual problem. (or potentially both of these).

When clicking through games really fast I occasionally see the sidebar panel flicker (where its lazy-loading data in the background). Is this what you mean?

If not, perhaps you could use a free screenrecorder (like OBS studio) and post a really should video of what you are seeing?

Many thanks,

-Asni

**Comment by WizLizard** [comment] 2017-09-27 10:47
I will record it. I know that it never happened a few releases back so it's
definitely a bug.

**Comment by Asnivor** [comment] 2017-09-27 10:49
Cool. A few versions back when you clicked on a game you had to wait for the sidebar to load all its data before you could click on another game. This was changed to 'lazy load' the sidebar data and increase responsiveness. I'm guessing this bug is something to do with that.

Thanks

**Comment by SteveBurgess** [comment] 2017-09-27 18:09
Is it the same as is happening in this gif?

https://gfycat.com/UnselfishAlarmedAfricanwildcat

**Comment by WizLizard** [comment] 2017-09-27 18:14
Yes that weird jumping never use to haopen.

**Comment by SteveBurgess** [comment] 2017-09-27 18:35
Here is a super slow mo version. 

https://gfycat.com/opulentsnappygazelle

Looks like the details pane disappears temporarily causing the search bar etc. to run over. It happens so quickly it looks like the text is jumping about.

**Comment by Asnivor** [comment] 2017-09-27 19:31
https://github.com/Asnivor/MedLaunch/blob/master/MedLaunch/Classes/VisualHandlers/GamesLibraryVisualHandler.cs#L42

That is being called first whenever the selected game changes. WPF auto-sizing shinanigans i imagine.

**Comment by Asnivor** [comment] 2017-09-29 10:37
Fixed in PR #191 by @SteveBurgess 

@WizLizard the fix is now available in the latest dev build if you want to try it? Not sure when the next production release will be:

https://ci.appveyor.com/project/Asnivor/medlaunch/build/ML-0.5.18.3-DEV-95/artifacts

**Comment by WizLizard** [comment] 2017-09-30 21:14
Ok i tested. Seems mostly fixed but boxart still seems a bit jumpy now. Could just be me being picky.

**Comment by Asnivor** [comment] 2017-10-01 08:08
Excellent.

Yeah, the boxart is probably always going to be jumpy to be honest. Its the time that takes it to load in.

The alternative is to not show the sidebar content at all until everything has loaded in. But that will take a lot of work. I'll make a note and see if it can be looked at in the future.

**Closed** 2018-01-15 14:48 UTC
Labels: available (fixed) in dev build, bug
