### ISSUE TITLE
Controller config menu not rendering correctly. Does not render bottom half of window

### ISSUE THREAD

**Issue by T00fy** [Asnivor/MedLaunch#197] opened 2018-01-28 06:53 UTC
![image](https://user-images.githubusercontent.com/12580207/35479786-74cf401a-0464-11e8-8188-5b068987bd4a.png)

See screenshot. Not sure if there's supposed to be an "Ok" or "Cancel" button shown here.

Thought it might have something to do with windows DPI scaling, so I disabled that setting but it still looks the same.

**Comment by Asnivor** [comment] 2018-01-28 10:45
Its likely just a minimum resolution thing where I need to tweak the UI.

Can you tell me what your desktop resolution is?

**Comment by Asnivor** [comment] 2018-01-29 09:58
This should now be fixed in the latest dev release:  https://medlaunch.info/downloads

The controller configuration window now instantiates based on the current main window height.

POC:

![image](https://user-images.githubusercontent.com/7911038/35504364-c9dff326-04da-11e8-90bc-a87aff63aa81.png)

![image](https://user-images.githubusercontent.com/7911038/35504396-db559890-04da-11e8-91e4-da89114fd232.png)

![image](https://user-images.githubusercontent.com/7911038/35504428-f15c2834-04da-11e8-96fe-aaa643013c7f.png)

**Comment by T00fy** [comment] 2018-01-29 11:01
I'm running this on an HD TV at 1920x1080. I'll try out the latest build soon

**Comment by Asnivor** [comment] 2018-01-29 11:05
OK cool. It *should* work now. Let me know if not and I'll have to test further.

**Comment by jjfmz42015** [comment] 2018-02-02 13:48
i looked at this and tested it out with the old build the problem is there with the current dev build all is good.

**Comment by Asnivor** [comment] 2018-02-02 14:19
Great, thanks for testing.

I'll push out a production release at some point over the next week or so.

Cheers,

-Asni

**Closed** 2018-03-02 15:33 UTC
Labels: available (fixed) in dev build, bug
